### ISSUE TITLE
Porting this page to AL CN Wiki 移植页面到碧蓝航线wiki

### ISSUE THREAD

**Issue by FlandreCirno** [x94fujo6rpg/AzurLaneFleet#3]
Hello, I'm FlandreCirno, one of Azur Lane CN Wiki editors. Recently I'm planning to rework our fleet page, while I saw you added MIT license to this project. So I'm interested in porting your page to CN Wiki. Is there anything else you want to request us to do?

你好，我是碧蓝海事局编辑组芙兰朵露琪露诺，我想翻新我们的舰队模拟页面，看到你的项目之前增加了MIT协议，所以想把你的页面移植到碧蓝航线Wiki上，请问你有什么其他的要求吗？

**Comment by x94fujo6rpg** [comment]
雖然大部分人上不了，可以的話還是留個這邊的git連接

由於開發過程是找到什麼用什麼，很多地方其實可以用更好的方式處理
只是因為功能已完成且能正常使用就放著了
有一些東西跟官方資料不完全相同，像船的ID之類

如果有其他問題可以這邊問或是discord `SilentRain#0980`

順便一個這幾天寫的腳本
https://github.com/x94fujo6rpg/SomeTampermonkeyScripts/blob/master/az_cn_wiki_fleet_tech_tool.user.js
作用於
https://wiki.biligame.com/blhx/%E8%88%B0%E9%98%9F%E7%A7%91%E6%8A%80
主要是讓使用者可以儲存/快速查看已練完的船
應該只需要改一下儲存資料的部分就好
